name       : tree
version    : 2.1.0
release    : 7
source     :
    - https://gitlab.com/OldManProgrammer/unix-tree/-/archive/2.1.0/unix-tree-2.1.0.tar.gz : e9f829a03996451bcf90fae4fdee4285bece6dc1a89de92a3f8e6cad29e03c71
homepage   : https://gitlab.com/OldManProgrammer/unix-tree
license    : GPL-2.0-or-later
component  : system.utils
summary    : list contents of directories in a tree-like format.
description: |
    Tree is a recursive directory listing command that produces a depth indented listing of files, which is colorized ala dircolors if the LS_COLORS environment variable is set and output is to tty
build      : |
    %make
install    : |
    install -Dm00664 $workdir/doc/tree.1 $installdir/usr/share/man/man1/tree.1
    install -Dm00755 $workdir/tree $installdir/usr/bin/tree
