name       : tree
version    : 1.8.0
release    : 4
source     :
    - http://mama.indstate.edu/users/ice/tree/src/tree-1.8.0.tgz : 715d5d4b434321ce74706d0dd067505bb60c5ea83b5f0b3655dae40aa6f9b7c2
homepage   : http://mama.indstate.edu/users/ice/tree/
license    : GPL-2.0-or-later
component  : system.utils
summary    : list contents of directories in a tree-like format.
description: |
    Tree is a recursive directory listing command that produces a depth indented listing of files, which is colorized ala dircolors if the LS_COLORS environment variable is set and output is to tty
build      : |
    %make
install    : |
    %make_install prefix="$installdir/usr" MANDIR="$installdir/usr/share/man/man1"
