name        : tree
version     : 1.7.0
release     : 2
source      :
    - http://mama.indstate.edu/users/ice/tree/src/tree-1.7.0.tgz : 6957c20e82561ac4231638996e74f4cfa4e6faabc5a2f511f0b4e3940e8f7b12
homepage    : http://mama.indstate.edu/users/ice/tree/
license     :
    - GPLv2
summary     : list contents of directories in a tree-like format.
description : |
    Tree is a recursive directory listing command that produces a depth indented listing of files, which is colorized ala dircolors if the LS_COLORS environment variable is set and output is to tty
build      : |
    %make
install    : |
    %make_install prefix="$installdir/usr" MANDIR="$installdir/usr/share/man/man1"
